# 以下文件放Nacos Config，Data ID：mall-admin-web.yaml，Group：MEELEET_GROUP
server:
  port: 9990

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.meeleet.mall.admin.controller
  cloud:
    subscribed-services: meeleet-sys
  consumer:
    check: false

# springdoc api文档
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url:
      path: /swagger-ui.html
    oauth:
      client-id: client
      client-secret: 123456
      scopes: all
  oauth-flow:
    token-url: http://localhost:9999/meeleet-auth/oauth/token
    refresh-token-url: http://localhost:9999/meeleet-auth/oauth/refresh_token
  server-url: ${gateway.base-url}/${spring.application.name}
  show-actuator: true
  packages-to-scan: com.meeleet.mall.admin.controller
  info:
    version: 1.0.0

# MinIO 分布式文件系统
minio:
  default-bucket: ${spring.application.name}