server:
  port: 9999

spring:
  redis:
    host: 127.0.0.1
    database: 14
  cloud:
    gateway:
      discovery:
        locator:
          # 启用自动根据服务ID生成路由
          enabled: true
          # 设置路由的路径为小写的服务ID
          lower-case-service-id: true
      routes:
        - id: meeleet-auth
          uri: lb://meeleet-auth
          predicates:
            # 断言（条件判断，返回值是bool，满足条件的）可以自定义路由配置
            - Path=/meeleet-auth/**
          filters:
            # 在请求转发路径去掉一层
            - StripPrefix=1
        - id: mall-admin-web
          uri: lb://mall-admin-web
          predicates:
            # 断言（条件判断，返回值是bool，满足条件的）可以自定义路由配置
            - Path=/mall-admin-web/**
          filters:
            # 在请求转发路径去掉一层
            - StripPrefix=1
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    loadbalancer:
      ribbon:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key

# 白名单(忽略鉴权)配置
security:
  ignore:
    urls:
      # 认证
      - /meeleet-auth/oauth/**
      # 短信验证码
      - /meeleet-auth/sms-code/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /swagger-ui.html

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG